apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  containers:
    - name: stress-ng
      image: polinux/stress-ng
      args:
        [
          "--cpu",
          "6",
          "--cpu-load",
          "80",
          "--vm",
          "6",
          "--vm-bytes",
          "1G",
          "--timeout",
          "5m",
        ]
      resources:
        requests:
          cpu: "1500m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
  restartPolicy: Never
